### ISSUE TITLE
Errant ripple effect on page refocus

### ISSUE THREAD

**Issue by nik3daz** [PolymerElements/paper-checkbox#85] opened 2015-12-04 02:30 UTC
Go to

https://elements.polymer-project.org/elements/paper-checkbox?view=demo:demo/index.html&active=paper-checkbox

Click a checkbox.
Switch to another tab.
Switch back.
The checkbox ripples for no reason.

Clicking in the URL bar and then back into the webcontents instead of switching tabs also exhibits this behavior.

**Comment by notwaldorf** [comment] 2015-12-07 23:46
This has the same cause as https://github.com/PolymerElements/paper-button/issues/24

**Comment by cdata** [comment] 2016-01-27 23:41
Closing this as a dupe of PolymerElements/paper-button#24

**Closed by cdata** 2016-01-27 23:41 UTC
