### ISSUE TITLE
Hyperlinks within the label don't work when the checkbox is disabled.

### ISSUE THREAD

**Issue by shc023** [PolymerElements/paper-checkbox#166] opened 2016-12-09 01:00 UTC
### Description

When there are hyperlinks within paper-checkbox's labels, clicking on it should follow through to the href regardless of checkbox being enabled/disabled. However, currently the <a> tag is inheriting <paper-checkbox style="pointer-events:none"> (Possibly applied by https://github.com/PolymerElements/iron-behaviors/blob/master/iron-control-state.html#L90) and it's ignoring clicks.

### Expected outcome

Hyperlinks should still work when checkbox is disabled.

### Actual outcome

Clicks on hyperlinks are being ignored when checkbox is disabled.

### Example

https://jsfiddle.net/tzswf82b/

### Steps to reproduce

1. Put in page `<paper-checkbox disabled>Label <a href="http://polymer-project.org">link</a></paper-checkbox>`
2. Click the link.
3. Observe that nothing happens.

**Comment by notwaldorf** [comment] 2016-12-12 19:16
I thiiink that makes sense to me. The _entire_ element is disabled, which means both the checkbox and its label; in particular, in this case, you added a link to the label, but it should be disabled as well. 

If you don't want the checkbox and the link to be connected like this, you should use an `iron-label` element instead. Perhaps something like this:
```
<iron-label><paper-checkbox disabled></paper-checkbox>Label <a href="#">link</a><iron-label>
```

Closing, as this looks like intended behaviour (/cc @bicknellr )

**Closed by notwaldorf** 2016-12-12 19:16 UTC
Labels: source: hooli
